name: Python Workflow

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: Install dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install -r requirements.txt
      
      - name: Check changed files
        id: changed-files
        run: echo ::set-output name=files::$(git diff --name-only HEAD~1)

      - name: Run script
        run: |
          source .venv/bin/activate
          python main.py --input-file "${{ github.workspace }}/${{ steps.changed-files.outputs.files }}"
        env:
          GITHUB_WORKSPACE: ${{ github.workspace }}
      
      - name: Print output
        run: |
          cat ${{ github.workspace }}/output.txt
        if: success() && steps.create-output-file.outputs.file-created == 'true'
      
      - name: Create artifact
        if: success() && steps.create-output-file.outputs.file-created == 'true'
        uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: ${{ github.workspace }}/output_*.txt
      
      - name: Set output variable
        id: create-output-file
        run: |
          if [ -f ${{ github.workspace }}/output.txt ]; then echo "FILE_CREATED=true" >> $GITHUB_ENV; else echo "FILE_CREATED=false" >> $GITHUB_ENV; fi
