name: Python Workflow

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install -r requirements.txt

      - name: Run script
        id: run-script
        run: |
          source .venv/bin/activate
          export OUTPUT_CONTENT=$(python main.py ${GITHUB_WORKSPACE}/${{ steps.changed-files.outputs.files }})
        env:
          GITHUB_WORKSPACE: ${{ github.workspace }}

      - name: Print output
        run: |
          echo "${{ env.OUTPUT_CONTENT }}"

      - name: Create artifact
        uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: ${{ github.workspace }}/output.txt
