name: Python Workflow

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run script
        id: run-script
        run: |
          python main.py --input-file="${{ steps.changed-files.outputs.files }}" > output.txt
        env:
          GITHUB_WORKSPACE: ${{ github.workspace }}

      - name: Create artifact
        uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: ${{ steps.run-script.outputs.stdout }}
