name: Python Workflow

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: Install dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install -r requirements.txt
      
      - name: Check changed files
        id: changed-files
        uses: tj-actions/changed-files@v9
        with:
          files: |
            *.py
            *.json
      
      - name: Run script
        run: |
          source .venv/bin/activate
          python main.py ${GITHUB_WORKSPACE}/${{ steps.changed-files.outputs.files }}
        env:
          GITHUB_WORKSPACE: ${{ github.workspace }}
      
      - name: Display artifact path
        run: |
          echo "Artifact path: ${{ github.workspace }}/output.txt"
      
      - name: Print output
        run: |
          cat ${{ github.workspace }}/output.txt
      
      - name: Set output variable
        id: output
        run: |
          echo "MY_OUTPUT_VAR=$(echo ${{ github.workspace }}/output.txt)" >> $GITHUB_ENV
