name: Franklin Generation Workflow

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: Install dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install -r requirements.txt
      
      - name: Check changed files
        id: changed-files
        run: echo ::set-output name=files::$(git diff --name-only HEAD~1)

      - name: Run script and create output file
        run: |
          source .venv/bin/activate
          python test_docx.py --input-file="${{ steps.changed-files.outputs.files }}" --output-path="${{ github.workspace }}/document.docx"
        env:
          GITHUB_WORKSPACE: ${{ github.workspace }}
      
      - name: Print output
        run: |
          ls ${{ github.workspace }}
      
      - name: Create artifact
        uses: actions/upload-artifact@v2
        with:
          name: Created Document
          path: ${{ github.workspace }}/document.docx
