name: Python Script Pipeline

on:
  push:
    branches:
      - main

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Get changed files
        id: changed-files
        run: |
          echo "::set-output name=files::$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/commits/${{ github.event.head_commit.id }}" \
            | jq -r '.files[] | select(.status != "removed") | .filename')"

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install -r requirements.txt
      
      - name: Run script
        run: |
          json_file=$(echo "${{ steps.changed-files.outputs.files }}" | grep '.json')
          python main.py "$json_file"
      
      - name: Display artifact path
        run: echo "Artifact saved at $(pwd)/output.txt"
