name: Python Workflow

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install -r requirements.txt

      - name: Run script
        id: run-script
        run: |
          source .venv/bin/activate
          python main.py "${{ github.workspace }}/${{ github.event.inputs.input_file }}"
        env:
          GITHUB_WORKSPACE: ${{ github.workspace }}

      - name: Display artifact path
        if: success()
        run: |
          echo "Artifact path: ${{ github.workspace }}/${{ steps.run-script.outputs.artifact_file }}"

      - name: Print output
        if: success()
        run: |
          cat ${{ github.workspace }}/${{ steps.run-script.outputs.artifact_file }}

      - name: Upload artifact
        if: success()
        uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: ${{ github.workspace }}/${{ steps.run-script.outputs.artifact_file }}
